[server]
PoolStart  = "192.168.0.100"
PoolEnd    = "192.168.0.200"
ServerPort = 67
ClientPort = 68

[fields]
OP     = 1
HTYPE  = 1
HLEN   = 6
HOPS   = 0
XID    = 0
SECS   = 0
FLAGS  = 0
CIADDR = "0.0.0.0"
YIADDR = "0.0.0.0"
SIADDR = "0.0.0.0"
GIADDR = "0.0.0.0"
CHADDR = "DEADBEEFCAFE"
SNAME  = "test string"
FILE   = "test string 2"

[options]
##############################
# RFC 1497 Vendor Extensions #
##############################
PAD  = true               #Option 0:   Pad (bool)
END  = true               #Option 255: End (bool)
SNM  = "255.255.255.0"    #Option 1:   Subnet Mask (string) (ip)
TOFF = 0                  #Option 2:   Time Offset (uint32)
RTR  = [ "192.168.0.1" ]  #Option 3:   Router ([]string) (ip)
TSVR = [ "192.168.0.1" ]  #Option 4:   Time Server ([]string) (ip)
NS   = [ "192.168.0.1" ]  #Option 5:   Name Server ([]string) (ip)
DNS  = [ "192.168.0.1" ]  #Option 6:   Domain Name Server ([]string) (ip)
LSVR = [ "192.168.0.1" ]  #Option 7:   Log Server ([]string) (ip)
CSVR = [ "192.168.0.1" ]  #Option 8:   Cookie Server ([]string) (ip)
LPRS = [ "192.168.0.1" ]  #Option 9:   Line Printer Server ([]string) (ip)
ISVR = [ "192.168.0.1" ]  #Option 10:  Impress Server ([]string) (ip)
RLS  = [ "192.168.0.1" ]  #Option 11:  Resource Location Server ([]string) (ip)
HN   = "hostname"         #Option 12:  Host Name (string)
BFS  = 33                 #Option 13:  Boot File Size (uint16)
MDF  = "file path"        #Option 14:  Merit Dump File (string) (NVT)
DN   = "domain name"      #Option 15:  Domain Name (string)
SS   = "192.168.0.1"      #Option 16:  Swap Server (string) (ip)
RP   = "path"             #Option 17:  Root Path (string) (NVT)
EP   = "path"             #Option 18:  Extensions Path (string)
################################
# IP Layer Parameters per Host #
################################
IPFW  = true                                   #Option 19: IP Forwarding Enable/Disable (bool)
NLSR  = true                                   #Option 20: Non-Local Source Routing (bool)
PF    = [ [ "192.168.0.1", "255.255.255.0" ] ] #Option 21: Policy Filter ([][2]string) (ip, snm)
MDRS  = 1500                                   #Option 22: Maximum Datagram Reassembly Size (uint16) (min:576)
IPTTL = 30                                     #Option 23: Default IP Time-to-live (uint16)
PMAT  = 300                                    #Option 24: Path MTU Aging Timeout Option (uint16)
PMPT  = [ 80, 77 ]                             #Option 25: Path MTU Plateau Table ([]uint16) (min:68)
#####################################
# IP Layer Parameters per Interface #
#####################################
IMTU   = 80                                    #Option 26: Interface MTU (uint16) (multiple) (min:68)
ASAL   = true                                  #Option 27: All Subnets are Local (bool)
BCADDR = "192.168.0.255"                       #Option 28: Broadcast Address (string) (ip)
PMD    = true                                  #Option 29: Perform Mask Discovery (bool)
MSUP   = true                                  #Option 30: Mask Supplier (bool)
PRD    = true                                  #Option 31: Perform Router Discovery (bool)
RSA    = "192.168.0.1"                         #Option 32: Router Solicitation Address (string) (ip)
SRT    = [ [ "192.168.0.10", "192.168.0.1" ] ] #Option 33: Static Route ([][2]string) (ip, ip)
#######################################
# Link Layer Parameters per Interface #
#######################################
TENCP = true #Option 34: Trailer Encapsulation (bool)
ACTIM = 600  #Option 35: ARP Cache Timeout (uint32)
EENCP = true #Option 36: Ethernet Encapsulation (bool)
##################
# TCP Parameters #
##################
TDTTL = 38   #Option 37: TCP Default TTL (uint8)
TKAI  = 0    #Option 38: TCP Keepalive Interval (uint32)
TKAG  = true #Option 39: TCP Keepalive Garbage (bool)
######################################
# Application and Service Parameters #
######################################
NISD  = "nisDomain"        #Option 40: Network Information Service Domain (string) (nvt)
NISVR = [ "192.168.0.1" ]  #Option 41: Network Information Servers ([]string) (ip)
NTPS  = [ "192.168.0.1" ]  #Option 42: Network Time Protocol Servers ([]string) (ip)
VSI   = [ 47, 7, 45 ]      #Option 43: Vendor Specific Information ([]byte)
NBNS  = [ "192.168.0.1" ]  #Option 44: NetBIOS over TCP/IP Name Server ([]string) (ip)
NBDDS = [ "192.168.0.1" ]  #Option 45: NetBIOS over TCP/IP Datagram Distribution Server ([]string) (ip)
NBNT  = 0x4                #Option 46: NetBIOS over TCP/IP Node Type (uint8)
NBS   = "scope"            #Option 47: NetBIOS over TCP/IP Scope (string)
XWSFS = [ "192.168.0.1" ]  #Option 48: X Window System Font Server ([]string) (ip)
XWSDM = [ "192.168.0.1" ]  #Option 49: X Window System Display Manager ([]string) (ip)
NISPD = "nisPlusDomain"    #Option 64: Network Information Service+ Domain (string)
NISPS = [ "192.168.0.1" ]  #Option 65: Network Information Service+ Servers ([]string) (ip)
MIPHA = [ "192.168.0.1" ]  #Option 68: Mobile IP Home Agent ([]string) (ip)
SMTPS = [ "192.168.0.1" ]  #Option 69: Simple Mail Transfer Protocol (SMTP) Server ([]string) (ip)
POP3S = [ "192.168.0.1" ]  #Option 70: Post Office Protocol (POP3) Server ([]string) (ip)
NNTPS = [ "192.168.0.1" ]  #Option 71: Network News Transport Protocol (NNTP) Server ([]string) (ip)
DWWWS = [ "192.168.0.1" ]  #Option 72: Default World Wide Web (WWW) Server ([]string) (ip)
DFS   = [ "192.168.0.1" ]  #Option 73: Default Finger Server ([]string) (ip)
DIRCS = [ "192.168.0.1" ]  #Option 74: Default Internet Relay Chat (IRC) Server ([]string) (ip)
STS   = [ "192.168.0.1" ]  #Option 75: StreetTalk Server ([]string) (ip)
STDAS = [ "192.168.0.1" ]  #Option 76: StreetTalk Directory Assiatance (STDA) Server ([]string) (ip)
###################
# DHCP Extensions #
###################
RIPA   = "192.168.0.1"  #Option 50: Requested IP Address (string) (ip)
IPALT  = 86400          #Option 51: IP Address Lease Time (uint32)
OPTOVR = 3              #Option 52: Option Overload (uint8) (1||2||3)
TFTPSN = "tftpName"     #Option 66: TFTP Server Name (string)
BFNAME = "bootFileName" #Option 67: Bootfile Name (string)
MSGTYP = 2              #Option 53: DHCP Message Type ## Not configurable, automatically choosen by server
SVRID  = "192.168.0.1"  #Option 54: Server Identifier (string) (ip)
PRL    = [ 1, 66, 18 ]  #Option 55: Parameter Request List ## Not configurable, used by client
MSG    = "errMsg"       #Option 56: Message (string) (nvt)
MAXMSG = 1024           #Option 57: Maximum DHCP Message Size (uint16) (min:576)
T1     = 43200          #Option 58: Renewal (T1) Time Value (uint32)
T2     = 43200          #Option 59: Rebinding (T2) Time Value (uint32)
VCID   = [ 45, 47, 7 ]  #Option 60: Vendor Class Identifier ([]byte)
CIDENT = [ 7, 45, 47 ]  #Option 61: Client-Identifier ([]byte)
